# Generated by Django 4.2.17 on 2025-02-02 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cage', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(editable=False, max_length=5, unique=True)),
                ('sent_at', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rfqs', to=settings.AUTH_USER_MODEL)),
                ('oem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='solicitations.oem')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cage', models.CharField(max_length=5)),
                ('nomenclature', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity', models.CharField(max_length=20)),
                ('NSN', models.CharField(default='1', max_length=20)),
                ('issued_date', models.CharField(max_length=20)),
                ('return_by_date', models.CharField(max_length=20)),
                ('organization_name', models.CharField(blank=True, max_length=20)),
                ('street_name', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='RFQReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_mode', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], max_length=5)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('short_note', models.TextField(blank=True, max_length=1000, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='replies/documents/')),
                ('is_viewed', models.BooleanField(default=False)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='solicitations.rfq')),
                ('rfq_creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='rfq_replies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rfq',
            name='solicitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='solicitations.solicitation'),
        ),
        migrations.CreateModel(
            name='OEMUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_disabled', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('oem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitations.oem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'oem')},
            },
        ),
        migrations.AddField(
            model_name='oem',
            name='users',
            field=models.ManyToManyField(related_name='oems', through='solicitations.OEMUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='I hope this message finds you well. We are currently looking for the following item. Kindly provide your lowest possible price.')),
                ('salutation', models.CharField(default='Dear Mr/Ms', max_length=20)),
                ('heading', models.CharField(default='REQUEST FOR QUOTATION', max_length=50)),
                ('userMail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
