# Generated by Django 4.2.17 on 2025-02-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubWorkflowSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(default=1)),
                ('minute', models.IntegerField(default=0)),
                ('day_of_week', models.CharField(default='*', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
