# Generated by Django 4.2.17 on 2026-02-09 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RfqAutoFetchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', help_text='Current status of the last auto-fetch run for this user', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the last auto-fetch run started for this user', null=True)),
                ('finished_at', models.DateTimeField(blank=True, help_text='When the last auto-fetch run finished for this user', null=True)),
                ('emails_scanned', models.PositiveIntegerField(default=0, help_text='How many email messages were scanned in the last run')),
                ('rfqs_created', models.PositiveIntegerField(default=0, help_text='How many RFQ replies were created in the last run')),
                ('errors_count', models.PositiveIntegerField(default=0, help_text='How many errors occurred in the last run')),
                ('message', models.CharField(blank=True, help_text='Short human-readable summary of the last run status', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_auto_fetch_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RFQ Auto-Fetch Status',
                'verbose_name_plural': 'RFQ Auto-Fetch Statuses',
            },
        ),
    ]
