# Generated by Django 4.2.17 on 2025-01-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oemuser',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
