# Generated by Django 4.2.17 on 2025-01-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqreply',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
    ]
