# Generated by Django 4.2.17 on 2025-01-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0002_oemuser_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('salutation', models.CharField(max_length=10)),
                ('body', models.TextField()),
            ],
        ),
    ]
