# Generated by Django 4.2.17 on 2026-02-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0002_rfqautofetchstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplateconfig',
            name='show_items_col_index',
            field=models.BooleanField(default=True, help_text='Show # column in items table'),
        ),
        migrations.AddField(
            model_name='emailtemplateconfig',
            name='show_items_col_nomen',
            field=models.BooleanField(default=True, help_text='Show Nomen column'),
        ),
        migrations.AddField(
            model_name='emailtemplateconfig',
            name='show_items_col_nsn',
            field=models.BooleanField(default=True, help_text='Show NSN column'),
        ),
        migrations.AddField(
            model_name='emailtemplateconfig',
            name='show_items_col_part_no',
            field=models.BooleanField(default=True, help_text='Show Part# column'),
        ),
        migrations.AddField(
            model_name='emailtemplateconfig',
            name='show_items_col_qty_unit',
            field=models.BooleanField(default=True, help_text='Show Qty/Unit column'),
        ),
        migrations.AddField(
            model_name='emailtemplateconfig',
            name='show_items_col_solicitation_no',
            field=models.BooleanField(default=True, help_text='Show Solicitation# column'),
        ),
        migrations.AddField(
            model_name='emailtemplateconfig',
            name='show_items_col_total_price',
            field=models.BooleanField(default=True, help_text='Show Total Price (USD) column'),
        ),
        migrations.AddField(
            model_name='emailtemplateconfig',
            name='show_items_col_unit_price',
            field=models.BooleanField(default=True, help_text='Show Unit Price (USD) column'),
        ),
    ]
