# Generated by Django 4.2.17 on 2025-02-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0002_githubworkflowschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Extract Data Every 10 Minutes', max_length=255)),
                ('cron_schedule', models.CharField(default='0 1 * * *', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GitHubWorkflowSchedule',
        ),
    ]
