# Generated by Django 4.2.17 on 2025-01-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0002_rfqreply_is_replied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfqreply',
            old_name='is_replied',
            new_name='is_viewed',
        ),
    ]
