# Generated by Django 4.2.17 on 2025-03-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0003_githubworkflow_delete_githubworkflowschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='part_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='pr',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='unit',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
