# Generated by Django 4.2.17 on 2025-01-28 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0003_rename_is_replied_rfqreply_is_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitation',
            name='scraped_by',
        ),
    ]
