# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0003_add_items_table_column_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplateconfig',
            name='logo_width',
            field=models.PositiveIntegerField(default=120, help_text='Logo width in pixels (display size in email)'),
        ),
    ]
