# Generated by Django 4.2.17 on 2025-01-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0003_emailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(default='I hope this message finds you well. We are currently looking for the following item. Kindly provide your lowest possible price.'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='header',
            field=models.CharField(default='REQUEST FOR QUOTATION', max_length=50),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='salutation',
            field=models.CharField(default='Dear Mr/Ms', max_length=10),
        ),
    ]
