# Generated by Django 4.2.17 on 2025-01-08 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0004_alter_emailtemplate_body_alter_emailtemplate_header_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
