# Generated by Django 4.2.17 on 2025-03-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0004_solicitation_part_number_solicitation_pr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oem',
            name='user_edits',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
