# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0004_emailtemplateconfig_logo_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplateconfig',
            name='banner_bg_color',
            field=models.CharField(default='#1e3a8a', help_text='Header banner background (hex)', max_length=7),
        ),
    ]

