# Generated by Django 4.2.17 on 2025-01-28 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0004_remove_solicitation_scraped_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='solicitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='solicitations.solicitation'),
        ),
    ]
