# Generated by Django 4.2.17 on 2025-03-19 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0005_oem_user_edits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oem',
            name='user_edits',
        ),
    ]
