# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0005_emailtemplateconfig_banner_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplateconfig',
            name='header_text_color',
            field=models.CharField(default='#000000', help_text='Table header text color (hex)', max_length=7),
        ),
    ]

