# Generated by Django 4.2.17 on 2025-01-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0005_alter_rfq_solicitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='fax',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='organization_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='street_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
