# Generated by Django 4.2.17 on 2025-01-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0006_solicitation_city_solicitation_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitation',
            name='issued_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='return_by_date',
            field=models.DateField(),
        ),
    ]
