# Generated by Django 4.2.17 on 2025-03-19 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitations', '0006_remove_oem_user_edits'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOEMCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, max_length=50, null=True)),
                ('custom_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('custom_phone', models.CharField(blank=True, max_length=14, null=True)),
                ('custom_fax', models.CharField(blank=True, max_length=20, null=True)),
                ('custom_city', models.CharField(blank=True, max_length=50, null=True)),
                ('custom_street', models.CharField(blank=True, max_length=50, null=True)),
                ('custom_postal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('oem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitations.oem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'oem')},
            },
        ),
    ]
