# Generated by Django 4.2.17 on 2025-01-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0007_alter_solicitation_issued_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitation',
            name='issued_date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='return_by_date',
            field=models.CharField(max_length=20),
        ),
    ]
