# Generated by Django 4.2.17 on 2026-03-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0007_emailtextstyleoverride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplateconfig',
            name='layout_style',
            field=models.CharField(choices=[('classic', 'Classic - Traditional table layout'), ('two_column', 'Two Column - Side by side fields'), ('card_based', 'Card Based - Each section in cards'), ('compact', 'Compact - Single column condensed'), ('modern_grid', 'Modern Grid - Grid-based sections'), ('header_banner', 'Header Banner - Branded top banner')], default='classic', help_text='Email template layout design', max_length=20),
        ),
    ]
