# Generated by Django 4.2.17 on 2025-03-20 12:52

from django.db import migrations, models
import solicitations.models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0008_emailsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='send_time',
            field=models.TimeField(default=solicitations.models.get_default_send_time),
        ),
    ]
