# Generated by Django 4.2.17 on 2025-03-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0009_alter_emailsettings_send_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitation',
            name='part_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
