# Generated by Django 4.2.17 on 2026-03-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0009_emailtemplatehistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailtemplatehistory',
            new_name='solicitatio_user_id_fc6f7c_idx',
            old_name='solicitatio_user_id_31fd40_idx',
        ),
    ]
