# Generated by Django 4.2.17 on 2025-03-24 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitations', '0010_alter_solicitation_part_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitationEmailStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_attempts', models.IntegerField(default=0)),
                ('solicitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitations.solicitation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Solicitation Email Statuses',
                'unique_together': {('solicitation', 'user')},
            },
        ),
    ]
