# Generated by Django 4.2.17 on 2025-03-25 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0011_solicitationemailstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='solicitations.rfq')),
                ('solicitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_items', to='solicitations.solicitation')),
            ],
        ),
    ]
