# Generated by Django 4.2.17 on 2026-03-31 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0011_oemimportjob'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailtemplatehistory',
            new_name='solicitatio_user_id_31fd40_idx',
            old_name='solicitatio_user_id_fc6f7c_idx',
        ),
        migrations.RenameIndex(
            model_name='oemimportjob',
            new_name='solicitatio_user_id_9f9c35_idx',
            old_name='solicitatio_user_id_2d9d4f_idx',
        ),
    ]
