# Generated by Django 4.2.17 on 2026-04-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0012_rename_solicitatio_user_id_fc6f7c_idx_solicitatio_user_id_31fd40_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoScrapeQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('first', 'First'), ('second', 'Second')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auto scrape queue item',
                'verbose_name_plural': 'Auto scrape queue items',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['created_at'], name='solicitatio_created_675ad0_idx')],
            },
        ),
    ]
