# Generated by Django 4.2.17 on 2025-03-25 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitations', '0012_rfqitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQItemReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_mode', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], max_length=5)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('short_note', models.TextField(blank=True, max_length=1000, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='replies/item_documents/')),
                ('is_viewed', models.BooleanField(default=False)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_replies', to='solicitations.rfq')),
                ('rfq_creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='rfq_item_replies', to=settings.AUTH_USER_MODEL)),
                ('solicitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_item_replies', to='solicitations.solicitation')),
            ],
            options={
                'unique_together': {('rfq', 'solicitation', 'rfq_creator')},
            },
        ),
    ]
