# Generated by Django 4.2.17 on 2026-04-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0013_auto_scrape_queue_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='heading',
            field=models.CharField(default='REQUEST FOR QUOTATION', max_length=200),
        ),
    ]
