# Generated by Django 4.2.17 on 2025-03-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0014_rfqchat_rfqchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='last_processed',
            field=models.DateTimeField(blank=True, help_text='When emails were last processed for this user', null=True),
        ),
    ]
