# Generated by Django 4.2.17 on 2026-04-22 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0015_rfqidtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_of_quote', models.CharField(choices=[('email', 'Email'), ('fax', 'Fax'), ('mail', 'Mail')], default='email', max_length=20)),
                ('date_quote_received', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rfq_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='solicitations.rfqreply')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
