# Generated by Django 4.2.17 on 2025-05-06 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0015_emailsettings_last_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitationemailstatus',
            name='rfq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solicitations.rfq'),
        ),
        migrations.AddField(
            model_name='solicitationemailstatus',
            name='rfq_created',
            field=models.BooleanField(default=False),
        ),
    ]
