# Generated by Django 4.2.17 on 2026-04-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0016_bid_assessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfqreply',
            name='transport_cost',
        ),
        migrations.AddField(
            model_name='bidassessment',
            name='general_and_admin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bidassessment',
            name='minimum_order_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bidassessment',
            name='oem_delivery_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidassessment',
            name='oem_validity_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidassessment',
            name='other_oem_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bidassessment',
            name='package_and_pres_mtd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bidassessment',
            name='profit_margin_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='bidassessment',
            name='shipping_cost_to_vtx',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bidassessment',
            name='term',
            field=models.CharField(choices=[('net30', 'Net 30'), ('net45', 'Net 45'), ('net60', 'Net 60'), ('net90', 'Net 90'), ('2_10_net30', '2/10 Net 30'), ('cod', 'COD'), ('prepaid', 'Prepaid')], default='net30', max_length=20),
        ),
        migrations.AddField(
            model_name='bidassessment',
            name='total_shipping_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bidassessment',
            name='vertex_adjusted_rate',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bidassessment',
            name='vertex_delivery_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bidassessment',
            name='vertex_origin_inspection',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bidassessment',
            name='vertex_validity_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfqreply',
            name='oem_origin_inspection',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='OEM origin inspection cost', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='rfqreply',
            name='shipping_cost_to_destination',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Shipping cost to final destination', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='rfqreply',
            name='shipping_cost_to_manufacturer',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Shipping cost to manufacturer', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='bidassessment',
            name='source_of_quote',
            field=models.CharField(choices=[('email', 'Email'), ('fax', 'Fax'), ('phone', 'Phone'), ('portal', 'Portal'), ('mail', 'Mail')], default='email', max_length=20),
        ),
    ]
