# Generated by Django 4.2.17 on 2025-05-06 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0016_solicitationemailstatus_rfq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='scraped_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
