# Generated by Django 4.2.17 on 2026-04-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0017_rfqreply_shipping_fields_bidassessment_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidassessment',
            name='term',
            field=models.CharField(blank=True, choices=[('', '-- Select --'), ('1', 'Net 30'), ('10', '2% 10 Days'), ('3', '1/2% 20 Days'), ('6', '1/2% 10 Days'), ('8', '1/4% 20 Days')], default='1', max_length=20),
        ),
    ]
