# Generated by Django 4.2.17 on 2025-06-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0017_solicitation_scraped_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='solicitation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='NSN',
            field=models.CharField(default='1', max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='part_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='pr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='street_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
