# Generated by Django 4.2.17 on 2025-06-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0018_solicitation_solicitation_alter_solicitation_nsn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='acceptance_point',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='buyer_info',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='deliver_days',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='deliver_fob',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='inspection_point',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
