# Generated by Django 4.2.17 on 2026-04-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0018_bidassessment_term_field025'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidassessment',
            name='assessed',
            field=models.BooleanField(default=False, help_text='Mark this assessment as complete'),
        ),
    ]
