# Generated by Django 4.2.17 on 2025-06-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0019_solicitation_acceptance_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitation',
            name='part_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
