# Generated by Django 4.2.17 on 2026-04-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0019_bidassessment_assessed_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidassessment',
            name='oem_origin_inspection',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bidassessment',
            name='oem_unit_rate',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bidassessment',
            name='shipping_cost_to_destination',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bidassessment',
            name='shipping_cost_to_manufacturer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
