# Generated by Django 4.2.17 on 2025-06-24 19:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitations', '0020_alter_solicitation_part_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='smtp.sendgrid.net', max_length=255)),
                ('email_port', models.IntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_host_user', models.CharField(default='apikey', max_length=255)),
                ('email_host_password', models.CharField(max_length=255)),
                ('default_from_email', models.EmailField(max_length=254)),
                ('email_interval_seconds', models.IntegerField(default=10, help_text='Time delay between sending emails to different recipients (3-120 seconds)', validators=[django.core.validators.MinValueValidator(3, message='Minimum interval is 3 seconds'), django.core.validators.MaxValueValidator(120, message='Maximum interval is 2 minutes (120 seconds)')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
