# Generated by Django 4.2.17 on 2026-04-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0020_bidassessment_editable_oem_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidassessment',
            name='contract_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='bidassessment',
            name='margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='bidassessment',
            name='oem_calculated_rate',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='bidassessment',
            name='oem_origin_plus5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='bidassessment',
            name='total_material_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='bidassessment',
            name='vertex_calculated_rate',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True),
        ),
    ]
