# Generated by Django 4.2.17 on 2025-06-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0021_useremailconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
