# Generated by Django 4.2.17 on 2026-04-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0022_restructure_bidassessment_and_rfqreply_oem_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfqreply',
            name='other_costs',
        ),
    ]
