# Generated by Django 4.2.17 on 2025-09-01 12:46

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitations', '0022_alter_rfq_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQScriptLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=10)),
                ('category', models.CharField(choices=[('processing', 'Processing'), ('email', 'Email Operations'), ('error', 'Errors'), ('database', 'Database Operations'), ('oem', 'OEM Operations'), ('authentication', 'Authentication'), ('config', 'Configuration'), ('status', 'Status Updates'), ('summary', 'Summary'), ('lock', 'Lock Management'), ('validation', 'Validation'), ('cleanup', 'Cleanup Operations'), ('testing', 'Testing Mode'), ('debug', 'Debug Information')], db_index=True, default='processing', max_length=20)),
                ('message', models.TextField()),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('processing_mode', models.CharField(blank=True, choices=[('manual', 'Manual'), ('automated', 'Automated'), ('individual', 'Individual'), ('consolidated', 'Consolidated')], max_length=20, null=True)),
                ('solicitation_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('cage_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('rfq_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('oem_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('email_recipient', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('email_status', models.CharField(blank=True, max_length=50, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('items_processed', models.IntegerField(blank=True, null=True)),
                ('items_successful', models.IntegerField(blank=True, null=True)),
                ('items_failed', models.IntegerField(blank=True, null=True)),
                ('processing_duration', models.DurationField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional log data in JSON format')),
                ('script_version', models.CharField(blank=True, max_length=50, null=True)),
                ('source_function', models.CharField(blank=True, max_length=100, null=True)),
                ('source_line', models.IntegerField(blank=True, null=True)),
                ('is_testing_mode', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'rfq_script_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RFQScriptSession',
            fields=[
                ('session_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('interrupted', 'Interrupted')], default='running', max_length=20)),
                ('processing_mode', models.CharField(blank=True, choices=[('manual', 'Manual'), ('automated', 'Automated'), ('individual', 'Individual'), ('consolidated', 'Consolidated')], max_length=20, null=True)),
                ('total_solicitations_requested', models.IntegerField(default=0)),
                ('total_emails_sent', models.IntegerField(default=0)),
                ('total_failures', models.IntegerField(default=0)),
                ('total_warnings', models.IntegerField(default=0)),
                ('total_errors', models.IntegerField(default=0)),
                ('is_testing_mode', models.BooleanField(default=False)),
                ('auto_mode', models.BooleanField(default=False)),
                ('session_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'rfq_script_sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='RFQTaskSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('requested_solicitations', models.IntegerField(help_text='Total solicitations submitted for processing')),
                ('total_successful_sent', models.IntegerField(help_text='Number of RFQs successfully sent')),
                ('total_failed', models.IntegerField(help_text='Number of solicitations that failed')),
                ('date', models.DateField(help_text='Date when task was executed')),
                ('start_time', models.DateTimeField(help_text='When processing started')),
                ('completed_time', models.DateTimeField(help_text='When processing completed')),
                ('processing_mode', models.CharField(choices=[('manual', 'Manual'), ('automated', 'Automated')], max_length=20)),
                ('summary_email_sent', models.BooleanField(default=False)),
                ('summary_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RFQ Task Summary',
                'verbose_name_plural': 'RFQ Task Summaries',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProcessingControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_requested', models.BooleanField(default=False)),
                ('stop_reason', models.TextField(blank=True)),
                ('stop_requested_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSelectionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_ids', models.JSONField(default=list, help_text='List of selected solicitation IDs')),
                ('select_all_mode', models.BooleanField(default=False)),
                ('processing_ids', models.JSONField(default=list, help_text='List of currently processing IDs')),
                ('is_submitting', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('page_context', models.JSONField(default=dict, help_text='Current page context for filters')),
                ('current_page_url', models.CharField(blank=True, help_text='Current page URL', max_length=500)),
                ('filter_criteria', models.JSONField(default=dict, help_text='Active filters')),
                ('session_expires_at', models.DateTimeField(blank=True, help_text='When to auto-clear state', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rfqchat',
            name='rfq',
        ),
        migrations.RemoveField(
            model_name='rfqchatmessage',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='rfqchatmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='rfqitem',
            name='rfq',
        ),
        migrations.RemoveField(
            model_name='rfqitem',
            name='solicitation',
        ),
        migrations.AlterUniqueTogether(
            name='rfqitemreply',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rfqitemreply',
            name='rfq',
        ),
        migrations.RemoveField(
            model_name='rfqitemreply',
            name='rfq_creator',
        ),
        migrations.RemoveField(
            model_name='rfqitemreply',
            name='solicitation',
        ),
        migrations.RemoveField(
            model_name='rfqreply',
            name='rfq',
        ),
        migrations.RemoveField(
            model_name='rfqreply',
            name='rfq_creator',
        ),
        migrations.AlterModelOptions(
            name='useremailconfig',
            options={'verbose_name': 'User Email Configuration', 'verbose_name_plural': 'User Email Configurations'},
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='enable_time_1',
            field=models.BooleanField(default=True, help_text='Enable first time interval'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='enable_time_2',
            field=models.BooleanField(default=True, help_text='Enable second time interval'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='enable_time_3',
            field=models.BooleanField(default=False, help_text='Enable third time interval'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='send_scope',
            field=models.CharField(choices=[('all', 'Send all pending solicitations'), ('today', "Send only today's solicitations")], default='all', help_text='Choose which solicitations to send automatically', max_length=10),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='send_time_1',
            field=models.TimeField(default=datetime.time(9, 0), help_text='First time interval for sending RFQs'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='send_time_2',
            field=models.TimeField(default=datetime.time(14, 0), help_text='Second time interval for sending RFQs'),
        ),
        migrations.AddField(
            model_name='emailsettings',
            name='send_time_3',
            field=models.TimeField(default=datetime.time(18, 0), help_text='Third time interval for sending RFQs'),
        ),
        migrations.AddField(
            model_name='oem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='oem',
            name='data_source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('import', 'File Import'), ('script', 'Script Generated')], default='script', max_length=20),
        ),
        migrations.AddField(
            model_name='oem',
            name='manual_override',
            field=models.BooleanField(default=False, help_text='If True, this OEM data will not be updated by scripts'),
        ),
        migrations.AddField(
            model_name='oem',
            name='poc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='oem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='useremailconfig',
            name='custom_imap_host',
            field=models.CharField(blank=True, help_text='Custom IMAP server (leave blank for auto-detection)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useremailconfig',
            name='custom_imap_port',
            field=models.IntegerField(default=993, help_text='IMAP port (default: 993 for SSL)'),
        ),
        migrations.AddField(
            model_name='useremailconfig',
            name='custom_sent_folder',
            field=models.CharField(blank=True, help_text='Custom sent folder name (leave blank for auto-detection)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useremailconfig',
            name='max_emails_per_hour',
            field=models.IntegerField(default=20, help_text='Maximum emails to send per hour (conservative limit to avoid provider restrictions)', validators=[django.core.validators.MinValueValidator(1, message='Must allow at least 1 email per hour'), django.core.validators.MaxValueValidator(50, message='Maximum 50 emails per hour for safety')]),
        ),
        migrations.AddField(
            model_name='useremailconfig',
            name='save_to_sent_folder',
            field=models.BooleanField(default=True, help_text='Automatically save sent emails to the sent folder'),
        ),
        migrations.AddField(
            model_name='useroemcustomization',
            name='custom_poc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='oem',
            name='cage',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='oem',
            name='city',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='oem',
            name='fax',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='oem',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='oem',
            name='phone',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='oem',
            name='postal_code',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='oem',
            name='street',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='unique_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='useremailconfig',
            name='email_interval_seconds',
            field=models.IntegerField(default=10, help_text='Time delay between sending emails to different recipients (3-240 seconds)', validators=[django.core.validators.MinValueValidator(3, message='Minimum interval is 3 seconds'), django.core.validators.MaxValueValidator(240, message='Maximum interval is 4 minutes (240 seconds)')]),
        ),
        migrations.AlterField(
            model_name='useroemcustomization',
            name='custom_city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='useroemcustomization',
            name='custom_email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='useroemcustomization',
            name='custom_fax',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='useroemcustomization',
            name='custom_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='useroemcustomization',
            name='custom_phone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='useroemcustomization',
            name='custom_postal_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='useroemcustomization',
            name='custom_street',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='oem',
            index=models.Index(fields=['cage'], name='solicitatio_cage_e4ca49_idx'),
        ),
        migrations.AddIndex(
            model_name='oemuser',
            index=models.Index(fields=['user', 'is_disabled'], name='solicitatio_user_id_99acf5_idx'),
        ),
        migrations.AddIndex(
            model_name='oemuser',
            index=models.Index(fields=['oem', 'user', 'is_disabled'], name='solicitatio_oem_id_555f83_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitation',
            index=models.Index(fields=['scraped_date'], name='solicitatio_scraped_66c5f2_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitation',
            index=models.Index(fields=['-id'], name='solicitatio_id_974b59_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitation',
            index=models.Index(fields=['cage'], name='solicitatio_cage_481c93_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitation',
            index=models.Index(fields=['email'], name='solicitatio_email_109cbf_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitation',
            index=models.Index(fields=['organization_name'], name='solicitatio_organiz_a0cd42_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitation',
            index=models.Index(fields=['return_by_date'], name='solicitatio_return__f40e49_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitation',
            index=models.Index(fields=['scraped_date', '-id'], name='solicitatio_scraped_311528_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitation',
            index=models.Index(fields=['cage', 'scraped_date'], name='solicitatio_cage_540fac_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitation',
            index=models.Index(fields=['scraped_date', 'cage', 'email'], name='solicitatio_scraped_6ed51e_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitationemailstatus',
            index=models.Index(fields=['user', 'email_sent'], name='solicitatio_user_id_20c505_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitationemailstatus',
            index=models.Index(fields=['solicitation', 'user'], name='solicitatio_solicit_a6332e_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitationemailstatus',
            index=models.Index(fields=['user', 'solicitation', 'email_sent'], name='solicitatio_user_id_05b0df_idx'),
        ),
        migrations.DeleteModel(
            name='RFQChat',
        ),
        migrations.DeleteModel(
            name='RFQChatMessage',
        ),
        migrations.DeleteModel(
            name='RFQItem',
        ),
        migrations.DeleteModel(
            name='RFQItemReply',
        ),
        migrations.DeleteModel(
            name='RFQReply',
        ),
        migrations.AddField(
            model_name='userselectionstate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selection_state', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprocessingcontrol',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_control', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rfqtasksummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_task_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rfqscriptsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rfqscriptlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='rfqtasksummary',
            index=models.Index(fields=['user', '-start_time'], name='solicitatio_user_id_65ef26_idx'),
        ),
        migrations.AddIndex(
            model_name='rfqtasksummary',
            index=models.Index(fields=['date', '-start_time'], name='solicitatio_date_5ea374_idx'),
        ),
        migrations.AddIndex(
            model_name='rfqtasksummary',
            index=models.Index(fields=['processing_mode', '-start_time'], name='solicitatio_process_f8f6e2_idx'),
        ),
        migrations.AddIndex(
            model_name='rfqscriptlog',
            index=models.Index(fields=['timestamp', 'user'], name='rfq_script__timesta_da61c2_idx'),
        ),
        migrations.AddIndex(
            model_name='rfqscriptlog',
            index=models.Index(fields=['level', 'category'], name='rfq_script__level_aafe6a_idx'),
        ),
        migrations.AddIndex(
            model_name='rfqscriptlog',
            index=models.Index(fields=['task_id', 'timestamp'], name='rfq_script__task_id_0ae7b4_idx'),
        ),
        migrations.AddIndex(
            model_name='rfqscriptlog',
            index=models.Index(fields=['cage_code', 'timestamp'], name='rfq_script__cage_co_8e05cd_idx'),
        ),
        migrations.AddIndex(
            model_name='rfqscriptlog',
            index=models.Index(fields=['solicitation_id', 'timestamp'], name='rfq_script__solicit_2bd931_idx'),
        ),
        migrations.AddIndex(
            model_name='rfqscriptlog',
            index=models.Index(fields=['email_status', 'timestamp'], name='rfq_script__email_s_8e0c1c_idx'),
        ),
    ]
