# Generated by Django 4.2.17 on 2026-04-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0023_remove_rfqreply_other_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidassessment',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
