# Generated by Django 4.2.17 on 2025-09-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0023_rfqscriptlog_rfqscriptsession_rfqtasksummary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='enable_time_1',
            field=models.BooleanField(blank=True, default=True, help_text='Enable first time interval', null=True),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='enable_time_2',
            field=models.BooleanField(default=False, help_text='Enable second time interval'),
        ),
    ]
