# Generated by Django 4.2.17 on 2026-04-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0024_add_bidassessment_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidassessment',
            name='interest_type',
            field=models.CharField(choices=[('cod_cc', 'COD / CC'), ('50_50', '50/50'), ('cia_prepay', 'CIA / PREPAY')], default='cod_cc', max_length=20),
        ),
    ]
