# Generated by Django 4.2.17 on 2025-09-01 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0024_alter_emailsettings_enable_time_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsettings',
            name='enable_time_1',
            field=models.BooleanField(default=True, help_text='Enable first time interval'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='send_time_2',
            field=models.TimeField(blank=True, default=datetime.time(14, 0), help_text='Second time interval for sending RFQs', null=True),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='send_time_3',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Third time interval for sending RFQs', null=True),
        ),
    ]
