# Generated by Django 4.2.17 on 2026-05-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0025_add_bidassessment_interest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidassessment',
            name='unit_container',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
