# Generated by Django 4.2.17 on 2025-11-11 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitations', '0025_alter_emailsettings_enable_time_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RfqReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Reply'), ('received', 'Reply Received'), ('quoted', 'Quote Provided'), ('declined', 'Declined to Quote'), ('no_response', 'No Response')], default='received', help_text='Current status of the reply', max_length=20)),
                ('solicitation_number', models.CharField(blank=True, help_text='Solicitation number extracted from email', max_length=100)),
                ('rfq_unique_id', models.CharField(blank=True, db_index=True, help_text='RFQ ID extracted from email (e.g., ABC/MMDDYYYY/CAGE/000001)', max_length=100)),
                ('nsn', models.CharField(blank=True, help_text='NSN extracted from email', max_length=50)),
                ('nomenclature', models.TextField(blank=True, help_text='Nomenclature/description extracted from email')),
                ('quantity', models.CharField(blank=True, help_text='Quantity extracted from email', max_length=50)),
                ('unit', models.CharField(blank=True, help_text='Unit of measure extracted from email (e.g., EA, BOX)', max_length=20)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Unit price extracted from email', max_digits=12, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Total price extracted from email', max_digits=12, null=True)),
                ('oem_name', models.CharField(blank=True, help_text='OEM/Vendor name extracted from email', max_length=255)),
                ('replied_email', models.EmailField(blank=True, help_text='Email address the reply came from', max_length=254)),
                ('email_subject', models.CharField(blank=True, help_text='Email subject line', max_length=500)),
                ('email_body', models.TextField(blank=True, help_text='Full email body text')),
                ('received_date', models.DateTimeField(blank=True, help_text='When the email was received', null=True)),
                ('email_message_id', models.CharField(blank=True, help_text='Email Message-ID to prevent duplicates', max_length=500, unique=True)),
                ('has_attachments', models.BooleanField(default=False, help_text='Whether the email had attachments')),
                ('attachment_files', models.JSONField(blank=True, default=list, help_text='List of attachment file paths')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this reply')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rfq', models.ForeignKey(blank=True, help_text='Matched RFQ (if found by rfq_id)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oem_replies', to='solicitations.rfq')),
                ('user', models.ForeignKey(help_text='User who sent the RFQ and received this reply', on_delete=django.db.models.deletion.CASCADE, related_name='rfq_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RFQ Reply',
                'verbose_name_plural': 'RFQ Replies',
                'ordering': ['-received_date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-received_date'], name='solicitatio_user_id_f91533_idx'), models.Index(fields=['solicitation_number'], name='solicitatio_solicit_e5a62d_idx'), models.Index(fields=['rfq_unique_id'], name='solicitatio_rfq_uni_815c96_idx'), models.Index(fields=['status', '-received_date'], name='solicitatio_status_140996_idx'), models.Index(fields=['email_message_id'], name='solicitatio_email_m_1d69b5_idx'), models.Index(fields=['oem_name'], name='solicitatio_oem_nam_86dad5_idx'), models.Index(fields=['nsn'], name='solicitatio_nsn_1157b4_idx')],
            },
        ),
    ]
