# Generated by Django 4.2.17 on 2026-05-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0026_add_unit_container_to_bid_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidassessment',
            name='shipping_boxing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
