# Generated by Django 4.2.17 on 2025-11-12 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitations', '0026_rfqreply'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(help_text='Field position in export file (1-121)', unique=True)),
                ('column_name', models.CharField(help_text='Name of the field', max_length=255)),
                ('quote_level', models.CharField(blank=True, choices=[('header', 'Header'), ('line', 'Line'), ('product', 'Product'), ('', 'Not Applicable')], help_text='Quote level: Header, Line, or Product', max_length=20)),
                ('field_type', models.CharField(choices=[('mandatory', 'Mandatory'), ('conditional', 'Conditional'), ('optional', 'Optional'), ('reserved', 'Reserved')], help_text='Mandatory, Conditional, Optional, or Reserved', max_length=20)),
                ('max_length', models.IntegerField(default=0, help_text='Maximum length of the field value')),
                ('definition', models.TextField(blank=True, help_text='Field definition/description')),
                ('validation_rules', models.TextField(blank=True, help_text='Validation rules for this field')),
                ('default_value', models.CharField(blank=True, help_text='Default value for this field', max_length=255)),
                ('may_affect_bid_type', models.BooleanField(default=False, help_text='Whether this field may affect bid type')),
            ],
            options={
                'verbose_name': 'Export Field Definition',
                'verbose_name_plural': 'Export Field Definitions',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='UserExportConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether to include this field in export')),
                ('custom_value', models.CharField(blank=True, help_text='Custom static value for this field (overrides mapping)', max_length=255)),
                ('source_field', models.CharField(blank=True, help_text="Source field from Solicitation/RFQ model (e.g., 'solicitation', 'cage', 'NSN')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_configurations', to='solicitations.exportfielddefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_configurations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Export Configuration',
                'verbose_name_plural': 'User Export Configurations',
                'ordering': ['field_definition__position'],
            },
        ),
        migrations.AddIndex(
            model_name='exportfielddefinition',
            index=models.Index(fields=['position'], name='solicitatio_positio_d9de84_idx'),
        ),
        migrations.AddIndex(
            model_name='exportfielddefinition',
            index=models.Index(fields=['field_type'], name='solicitatio_field_t_57adac_idx'),
        ),
        migrations.AddIndex(
            model_name='userexportconfiguration',
            index=models.Index(fields=['user', 'field_definition'], name='solicitatio_user_id_202bc8_idx'),
        ),
        migrations.AddIndex(
            model_name='userexportconfiguration',
            index=models.Index(fields=['is_enabled'], name='solicitatio_is_enab_9c4bf8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userexportconfiguration',
            unique_together={('user', 'field_definition')},
        ),
    ]
