# Generated by Django 4.2.17 on 2025-11-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0027_exportfielddefinition_userexportconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportfielddefinition',
            name='predefined_choices',
            field=models.TextField(blank=True, help_text='JSON array of predefined choices for dropdown. Format: [{"value": "Y", "label": "Small Business Set-Aside"}, ...]'),
        ),
    ]
