# Generated by Django 4.2.17 on 2026-05-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0027_add_shipping_boxing_to_bid_assessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidassessment',
            name='admin_10pct_oem_origin',
        ),
    ]
