# Generated by Django 4.2.17 on 2026-05-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0028_remove_admin_10pct_oem_origin_from_bid_assessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfqreply',
            name='oem_origin_inspection',
        ),
        migrations.RemoveField(
            model_name='rfqreply',
            name='shipping_cost_to_destination',
        ),
        migrations.RemoveField(
            model_name='rfqreply',
            name='shipping_cost_to_manufacturer',
        ),
    ]
