# Generated by Django 4.2.17 on 2025-11-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0028_add_predefined_choices_to_export_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqreply',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='GPT-4 extraction confidence score (0.0 to 1.0)', null=True),
        ),
        migrations.AddField(
            model_name='rfqreply',
            name='extraction_notes',
            field=models.TextField(blank=True, help_text='GPT-4 extraction notes (missing fields, assumptions, etc.)'),
        ),
    ]
