# Generated by Django 4.2.17 on 2026-05-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0029_remove_oem_origin_inspection_shipping_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidassessment',
            name='packaging_inspection',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bidassessment',
            name='supplies_inspection',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
