# Generated by Django 4.2.17 on 2025-11-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0029_add_gpt4_extraction_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rfqreply',
            name='solicitatio_status_140996_idx',
        ),
        migrations.RemoveField(
            model_name='rfqreply',
            name='status',
        ),
        migrations.AddField(
            model_name='rfqreply',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final price after negotiations or adjustments', max_digits=12, null=True),
        ),
    ]
