# Generated by Django 4.2.17 on 2026-05-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0030_add_supplies_packaging_inspection_to_bid_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidassessment',
            name='shipping_cost_to_buyer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
