# Generated by Django 4.2.17 on 2025-11-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0030_remove_rfqreply_solicitatio_status_140996_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqreply',
            name='part_number',
            field=models.CharField(blank=True, help_text='Part number extracted from email', max_length=255),
        ),
    ]
