# Generated by Django 4.2.17 on 2025-11-28 13:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitations', '0031_rfqreply_part_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RfqAutoFetchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Enable automatic RFQ reply fetching from email')),
                ('fetch_time', models.TimeField(default=datetime.time(2, 0), help_text='Time of day to run auto-fetch (server timezone)')),
                ('days_back', models.PositiveSmallIntegerField(default=1, help_text='How many days back to search for RFQ replies each run')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_auto_fetch_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
