# Generated by Django 4.2.17 on 2026-05-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0031_add_shipping_cost_to_buyer_to_bid_assessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidassessment',
            name='margin',
        ),
    ]
