# Generated by Django 4.2.17 on 2025-11-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0032_rfqautofetchsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqautofetchsettings',
            name='day',
            field=models.CharField(choices=[('daily', 'Every day'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='daily', help_text='Which day(s) to run auto-fetch', max_length=20),
        ),
    ]
