# Generated by Django 4.2.17 on 2026-05-04 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0032_remove_margin_from_bid_assessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidassessment',
            name='company_origin_inspection',
        ),
    ]
