# Generated by Django 4.2.17 on 2026-05-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0033_remove_company_origin_inspection_from_bid_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidassessment',
            name='estimated_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
