# Generated by Django 4.2.17 on 2025-11-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0033_rfqautofetchsettings_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfqautofetchsettings',
            name='days_back',
            field=models.PositiveSmallIntegerField(default=2, help_text='How many days back to search for RFQ replies each run'),
        ),
    ]
