# Generated by Django 4.2.17 on 2025-11-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0034_alter_rfqautofetchsettings_days_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqautofetchsettings',
            name='last_fetched',
            field=models.DateTimeField(blank=True, help_text='When RFQ replies were last fetched for this user (prevents duplicate fetches)', null=True),
        ),
    ]
