# Generated by Django 4.2.17 on 2025-12-01 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0035_add_last_fetched_to_rfq_auto_fetch_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='RfqReplyExportOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rfq_reply', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='export_override', to='solicitations.rfqreply')),
            ],
            options={
                'verbose_name': 'RFQ Reply Export Override',
                'verbose_name_plural': 'RFQ Reply Export Overrides',
            },
        ),
    ]
