# Generated by Django 4.2.17 on 2025-12-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0036_rfqreplyexportoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqreply',
            name='exported_at',
            field=models.DateTimeField(blank=True, help_text='When this RFQ reply was last exported', null=True),
        ),
        migrations.AddField(
            model_name='rfqreply',
            name='is_exported',
            field=models.BooleanField(default=False, help_text='Whether this RFQ reply has been exported (archived)'),
        ),
    ]
