# Generated by Django 4.2.17 on 2025-12-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0037_rfqreply_exported_at_rfqreply_is_exported'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exportfielddefinition',
            index=models.Index(fields=['quote_level'], name='solicitatio_quote_l_735db4_idx'),
        ),
        migrations.AddIndex(
            model_name='exportfielddefinition',
            index=models.Index(fields=['field_type', 'position'], name='solicitatio_field_t_a8853e_idx'),
        ),
        migrations.AddIndex(
            model_name='exportfielddefinition',
            index=models.Index(fields=['column_name'], name='solicitatio_column__5cbbd5_idx'),
        ),
        migrations.AddIndex(
            model_name='rfqreplyexportoverride',
            index=models.Index(fields=['rfq_reply'], name='solicitatio_rfq_rep_00a97b_idx'),
        ),
        migrations.AddIndex(
            model_name='rfqreplyexportoverride',
            index=models.Index(fields=['updated_at'], name='solicitatio_updated_be39cf_idx'),
        ),
        migrations.AddIndex(
            model_name='userexportconfiguration',
            index=models.Index(fields=['user', 'is_enabled'], name='solicitatio_user_id_3ae70b_idx'),
        ),
        migrations.AddIndex(
            model_name='userexportconfiguration',
            index=models.Index(fields=['source_field'], name='solicitatio_source__8a35c0_idx'),
        ),
        migrations.AddIndex(
            model_name='userexportconfiguration',
            index=models.Index(fields=['updated_at'], name='solicitatio_updated_811da5_idx'),
        ),
    ]
