# Generated by Django 4.2.17 on 2025-12-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0038_add_export_models_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='purchase_request_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='solicitation_line_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
