# Generated by Django 4.2.17 on 2025-12-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0039_solicitation_purchase_request_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='is_set_aside',
            field=models.BooleanField(default=False),
        ),
    ]
