# Generated by Django 4.2.17 on 2025-12-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0040_solicitation_is_set_aside'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitation',
            name='is_set_aside',
            field=models.BooleanField(default=True),
        ),
    ]
