# Generated by Django 4.2.17 on 2026-06-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="added_days",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
