# Generated by Django 4.2.17 on 2026-07-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_added_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='added_days',
            field=models.IntegerField(blank=True, default=0, help_text='Days added to company delivery days on bid assessments'),
        ),
    ]
