# Generated by Django 4.2.17 on 2025-05-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_invitation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_initial',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
