# Generated by Django 4.2.17 on 2025-06-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_personal_work_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
