# Generated by Django 4.2.17 on 2025-06-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='personal_work_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
