# Generated by Django 4.2.17 on 2025-06-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_personal_work_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='personal_work_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
