# Generated by Django 4.2.17 on 2025-06-02 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_personal_work_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='personal_work_email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='title',
        ),
    ]
