# Generated by Django 4.2.17 on 2025-06-02 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_personal_work_email_customuser_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='personal_work_email',
        ),
    ]
