# Generated by Django 4.2.17 on 2025-09-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_personal_email'),
        ('accounts', '0016_customuser_personal_email'),
    ]

    operations = [
    ]
